name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config build-essential git zip unzip zlib1g-dev libncurses5-dev libffi-dev

    - name: Force Fix and Install Master p4a & Buildozer
      run: |
        python3 -m pip install --upgrade pip
        # تثبيت أحدث نسختين تطوريتين من buildozer و python-for-android لحل مشكلة libffi تماماً
        pip install --upgrade buildozer
        pip install --upgrade git+https://github.com/kivy/python-for-android.git@master

    - name: Run Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
